docs: add dynamic routes page
tuono-labs/tuono pull request #219
Opened 2024-12-11 07:55 UTC by Valerioageno

## Context & Description

2024-12-11 13:00 UTC, marcalexiei submitted a review, later dismissed
I created a separate commit with some improvements.
Let me know what you think about them!

2024-12-12 08:23 UTC, Valerioageno commented on apps/documentation/src/routes/documentation/routing/dynamic-routes.mdx
> +You are going to probably use something like:
I'm not a fan of "personalizing" the documentation by pointing directly the reader. 
I'll think about a rephrase over this sentence

2024-12-14 10:52 UTC, marcalexiei requested changes

2024-12-14 10:52 UTC, marcalexiei commented on apps/documentation/src/routes/documentation/routing/dynamic-routes.mdx
> +The dynamic segment can be used in both folder and file name:
```suggestion
The dynamic segment can be used in folders and files as well:
```

2024-12-14 10:52 UTC, marcalexiei commented on apps/documentation/src/routes/documentation/routing/dynamic-routes.mdx
> +The same path can have multiple dynamic segments:
```suggestion
A path can contain multiple dynamic segments, allowing for more flexible routing.
```

2024-12-15 12:39 UTC, merged